### ISSUE TITLE
PvP Support

### ISSUE THREAD

**Issue by SirUmnei** [PunishedPineapple/Distance#10]
Hi there. Been using this for a lil while, and can't help but notice, it doesn't work on PvP situations. Would be pretty useful to be able to tell distance to players, since I often play BRD/MCH. Possibility this can be included? Or if it is and I'm dumb?

**Comment by PunishedPineapple** [comment]
Unfortunately, this plugin specifically disables distance measurements in PvP areas.  The Dalamud maintainers have requested that plugins not provide any assistance in PvP, so most main repo plugins are set up like this.

**Comment by SirUmnei** [comment]
Ahhh I didn't know. I understand why though. Thanks for the quick reply.
