### ISSUE TITLE
HP numbers

### ISSUE THREAD

**Issue by HoshinoSenoku** [PunishedPineapple/Distance#13]
I would like to know how the HP numbers below the target bar in /docs/Images/image1.png are implemented. Is this a function of this plugin?

**Comment by PunishedPineapple** [comment]
HP numbers are from the Simple Tweaks plugin:
![image](https://user-images.githubusercontent.com/50609717/219512254-45ece222-7d9c-472f-bf80-74fb511e997e.png)

**Comment by HoshinoSenoku** [comment]
Thank you!
