### ISSUE TITLE
Anabaseios: The Eleventh Circle (Savage) Aggro Distance

### ISSUE THREAD

**Issue by memoriesKB** [PunishedPineapple/Distance#17]
Instance/Zone Name: Anabaseios: The Eleventh Circle (Savage)
Boss Name: Themis
BNpc ID: 12388
TerritoryType: 1152
Aggro Distance (to Ring): 4.97

P.S: Sometimes the boss has aggro only at 4.967, sometimes at 4.968 and 4.969, I don't really understand why.

**Comment by PunishedPineapple** [comment]
Thank you!  I've added this to the data, so you can update from the plugin settings window if you want.

As far as the imprecision goes, I'm not really certain.  My best guess is that the game just uses low precision at some point in the distance calculation process, so possibly subtly different angles have different results for the game.  Most likely, it gets packed into an integer representation with thousandths of a yalm precision by the game somewhere along the line (i.e., an X coordinate of 123.4567 is truncated to an integer of 123456).  I've seen it do this for some other things (like waymarks), so I would not be at all surprised if this happens for game object positions as well.  The plugin does not do this, which could be the source of the discrepancy.  I'm sorry to say that I won't be investigating this, as I'm not really doing any plugin development anymore besides trying to keep things running to the extent that I can.

You actually provided way more precision than I expect btw.  I might need to update the readme, but based on all the data points I have, it's all essentially whole yalms from the ring, with +0y, -0.1y precision.
