### ISSUE TITLE
Anabaseios: The Twelfth Circle (Savage) (Phase 1) Aggro Distance

### ISSUE THREAD

**Issue by memoriesKB** [PunishedPineapple/Distance#18]
Instance/Zone Name: Anabaseios: The Twelfth Circle (Savage) (Phase 1)
Boss Name: Athena
BNpc ID: 12377
TerritoryType: 1154
Aggro Distance (to ring): 6y

**Comment by PunishedPineapple** [comment]
Added.  Thanks again for the help!
