### ISSUE TITLE
Max melee arc

### ISSUE THREAD

**Issue by HaySome22** [PunishedPineapple/Distance#19]
I believe this isn't currently supported, but I may be wrong. The idea is to have an arc 3y away from the boss similar to the aggro arc and standing inside it ensures max melee.

**Comment by PunishedPineapple** [comment]
This is something that I had wanted to add in the form of arbitrary custom arcs like the current custom widgets, with a default for 3.5y max melee, but I basically have given up trying to do any of my hack fraud dev work unless it is just to address any significant latent issues.

If things ever changed, I would add it, but it would be best to not expect it.  I am sorry for the disappointment.

**Comment by PunishedPineapple** [comment]
This is now in the current *testing* version of the plugin (1.1.0.0).

If you open the plugin settings window and go to the "Custom Arcs" tab, press the "+" button, and it should add an arc that is set up by default to show max melee on your target.  Can be configured however else you want.

**Comment by HaySome22** [comment]
I got around to testing it and it's great, thank you!

**Comment by PunishedPineapple** [comment]
Now in the release channel.
