### ISSUE TITLE
Adoption

### ISSUE THREAD

**Issue by Infiziert90** [PunishedPineapple/Distance#21]
Hi,

saw that you made some more code changes after giving the project up for adoption, so wanted to make sure that it is still up for adoption :)
If yes, i would take it over

**Comment by PunishedPineapple** [comment]
I have some unfinished local changes because I just couldn't help myself.  I need to decide whether I want to abandon them or not, so let me think about it.  I am sorry.  I merged the API 9 updates here and will PR the plugin to D17 for now though.

**Comment by Infiziert90** [comment]
That is fine :)
