### ISSUE TITLE
The unit of distance

### ISSUE THREAD

**Issue by xyzsys** [PunishedPineapple/Distance#25]
Hi! I would like to be able to use meters instead of yards as the unit of distance to be displayed. Thank you!

**Comment by PunishedPineapple** [comment]
I am sorry, but the game uses yalms internally and for all tooltips, so showing them as meters would be displaying incorrect values and/or units.

**Comment by PunishedPineapple** [comment]
I see.  I have not opened up a non-English client for a while, so I should not have spoken so definitively before looking.  I kinda messed up.  I will have it match the game client.  Having correct units displayed is actually very important to me.

**Comment by PunishedPineapple** [comment]
It should now use meters for the Japanese client (German and French appear to use Yalms) in version 1.1.3.0, which just got merged.  Please let me know if you find any issues or something that I may have missed.

I apologize again for dismissing this issue without completely looking into it first.

**Comment by xyzsys** [comment]
Thanks for the ultra fast update. It seems to be working flawlessly. Great job!

After that I noticed that you are also the developer of WaymarkPresetPlugin. Your WPP repository is archived, are you no longer involved in its development?

**Comment by PunishedPineapple** [comment]
I stopped working on plugins about a year ago, and put all of mine up for adoption then.  Someone took over Waymark Preset Plugin and Ready Check Helper at that time, but nobody wanted the other two.  I've been doing a little bit of stuff again lately, but those two are under [someone else's](https://github.com/Infiziert90) control now.

**Comment by xyzsys** [comment]
I see. I'm glad you've resumed development even if only a little, since all the plug-ins you've developed have been excellent. If you ever need Japanese translations, feel free to contact me. Take care!

**Comment by PunishedPineapple** [comment]
Thank you very much for your kind words!  I will look into setting up for translation again once things have slowed down for the patch.
