### ISSUE TITLE
Another Aloalo Island and Another Aloalo Island (Savage) Agro Distances

### ISSUE THREAD

**Issue by Eszx** [PunishedPineapple/Distance#27]
TerritoryType: 1179
Ketuduke (BNpc ID: 12605)
pulls under 7y
Distance to ring: 6.987 (did not pull)

Lala (BNpc ID: 12639)
pulls under 10y
Distance to ring: 10.145

Statice (BNpc ID: 12506)
pulls under 10y
Distance to ring: 10.195

**Comment by PunishedPineapple** [comment]
These have been pushed and should be there the next time you start the game or reload the plugin (unless you have automatic downloads turned off for the aggro data).  There's also a button in the plugin settings to force checking for an update.  Thank you for submitting these numbers.
