### ISSUE TITLE
Change font color on Distance Threshold

### ISSUE THREAD

**Issue by Zeffuro** [PunishedPineapple/Distance#3]
This would be a nice function to have to have it like change color if you're in melee range for example and stuff.

**Comment by PunishedPineapple** [comment]
This is on my [to do list](https://github.com/PunishedPineapple/Distance/blob/main/Distance/ToDo.txt).  I just haven't gotten to it yet.  The plan is to make it like the caution and warning distances for the aggro widget.

**Comment by PunishedPineapple** [comment]
Generic widgets can be configured for distance-based coloring as of 0.9.8.0.
