### ISSUE TITLE
Random Numbers on first install

### ISSUE THREAD

**Issue by FatNibble** [PunishedPineapple/Distance#6]
Hi there,

Thanks for the Plugin, adds good info without being intrusive.

Found a minor bug that when first installed through Dalamud's Plugin Installer. The Plugin placed random numbers on enemies, NPCs & other players, these numbers were static and did not update with distance. Restarting the game fixed it completely so it's a Non-issue but thought you might like to know. If you'd like my Plugin list or anything let me know happy to help.

![2022-07-31 12_23_09-FINAL FANTASY XIV](https://user-images.githubusercontent.com/99473849/182010464-0820945e-ba51-4fe1-8e3c-6f8eae8be9dc.png)
![2022-07-31 12_08_03-FINAL FANTASY XIV](https://user-images.githubusercontent.com/99473849/182010468-10383f39-3f0e-4147-ae32-5a20252a3641.png)
![2022-07-31 12_16_16-FINAL FANTASY XIV](https://user-images.githubusercontent.com/99473849/182010472-b41b9239-21e6-47fc-8de1-4d02b5f85226.png)

**Comment by PunishedPineapple** [comment]
That very much looks to me like either the plugin got installed twice on top of each other somehow, or it hard crashed without being able to clean up and dispose its nodes, leaving orphan text nodes attached to the nameplates.

If you want to send me your log in the goat place discord and ping me (Banana Bread in there), I can take a look, but honestly if you don't ever see it happen again, I probably won't look too much into it, as Dalamud's been going through some changes with the installer lately, and I've had multiple instances of the same plugin end up running at the same time, causing issues like this.

**Comment by PunishedPineapple** [comment]
This was almost certainly a fluke, probably double plugin loading when the installer was sometimes doing that.
